server {
    listen 80;
    listen [::]:80;

    server_name xiaoshoufupan.woshimake.com;

    root /var/www/xiaoshoufupan-placeholder;
    index index.html;

    access_log /var/log/nginx/xiaoshoufupan.access.log;
    error_log /var/log/nginx/xiaoshoufupan.error.log;

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
