import { useEffect, useState } from 'react'
import { getCustomers, getTodos, updateTodo } from '../api/client.ts'
import { EmptyState, ErrorState, LoadingState } from '../components/PageStates.tsx'
import { sortTodos } from '../lib/todoSchedule.ts'
import type { CustomerRecord, TodoRecord } from '../types/types.ts'

type State = { status: 'loading' } | { status: 'error' } | { status: 'ready'; todos: TodoRecord[]; customers: CustomerRecord[] }

export default function TodoPage({ onNavigate }: { onNavigate: (path: string) => void }) {
  const [key, setKey] = useState(0); const [state, setState] = useState<State>({ status: 'loading' }); const [saving, setSaving] = useState<number | null>(null); const [message, setMessage] = useState('')
  useEffect(() => { let active = true; Promise.all([getTodos(), getCustomers()]).then(([todos, customers]) => { if (active) setState({ status: 'ready', todos, customers }) }).catch(() => { if (active) setState({ status: 'error' }) }); return () => { active = false } }, [key])
  if (state.status === 'loading') return <LoadingState message="正在加载待办…" />
  if (state.status === 'error') return <ErrorState title="待办加载失败" message="请检查后端服务后重试。" onRetry={() => { setState({ status: 'loading' }); setKey((v) => v + 1) }} />
  const names = new Map(state.customers.map((customer) => [customer.id, customer.name]))
  async function save(id: number, values: { done?: boolean; dueDate?: string | null }) { setSaving(id); setMessage(''); try { const updated = await updateTodo(id, values); setState((current) => current.status === 'ready' ? { ...current, todos: current.todos.map((todo) => todo.id === id ? updated : todo) } : current); setMessage('待办已保存，刷新后仍会保留。') } catch { setMessage('保存失败，请重试。') } finally { setSaving(null) } }
  return <section aria-labelledby="page-title"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-emerald-700">行动清单</p><h1 id="page-title" className="mt-2 text-3xl font-black">待办</h1><p className="mt-2 text-sm text-slate-500">没有明确日期的待办如实显示“未设截止日”。</p></div><button onClick={() => onNavigate('/new')} className="rounded-xl bg-emerald-700 px-4 py-3 text-sm font-black text-white">创建拜访日程</button></div>{message && <p role="status" className="mt-4 rounded-xl bg-slate-100 p-3 text-sm font-bold">{message}</p>}{state.todos.length === 0 ? <div className="mt-6"><EmptyState title="还没有待办" message="复盘动作会出现在这里。" /></div> : <ul className="mt-6 space-y-4">{sortTodos(state.todos).map((todo) => <li key={todo.id} className={`rounded-2xl border bg-white p-5 shadow-sm ${todo.done ? 'border-slate-200 opacity-65' : 'border-emerald-200'}`}><div className="flex items-start gap-3"><input aria-label={`完成待办：${todo.text}`} type="checkbox" checked={todo.done} disabled={saving === todo.id} onChange={(event) => void save(todo.id, { done: event.target.checked })} className="mt-1 h-5 w-5" /><div className="min-w-0 flex-1"><p className={`font-black ${todo.done ? 'line-through' : ''}`}>{todo.text}</p><p className="mt-2 text-sm text-slate-500">客户：{names.get(todo.customerId) ?? '客户不存在'} · {todo.dueDate ?? '未设截止日'}</p><form className="mt-3 flex flex-wrap gap-2" onSubmit={(event) => { event.preventDefault(); const value = new FormData(event.currentTarget).get('dueDate'); void save(todo.id, { dueDate: value ? String(value) : null }) }}><input name="dueDate" aria-label={`设置截止日：${todo.text}`} type="date" defaultValue={todo.dueDate ?? ''} className="rounded-lg border border-slate-200 px-3 py-2 text-sm" /><button disabled={saving === todo.id} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white disabled:opacity-40">{saving === todo.id ? '保存中…' : '设置截止日'}</button></form></div></div></li>)}</ul>}</section>
}
